# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw2_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.8.2'
pod 'Kingfisher', '~> 5.0'

  # Pods for hw2_Login

end
